### ISSUE TITLE
Wrong order of javascript in file django_nvd3/templatetags/nvd3_tags.py

### ISSUE THREAD

**Issue by jdehaan** [areski/django-nvd3#63] opened 2015-10-22 12:01 UTC
Commit f223546ac674f9871d6f893ce7d29b4b016c9ca4 introduces an issue regarding the ordering of javascripts. The order is relevant because scripts depend on each other. So the order has to be well defined and respected during the generation of the html code.

See: https://github.com/areski/django-nvd3/commit/f223546ac674f9871d6f893ce7d29b4b016c9ca4

D3 has to be first. by making the scripts be in a dictionary the order is not guaranteed to be the same as in the past version. Actually it turns out that the order is not correct on my machine leading d3 to be undefined for nvd3 code.

**Comment by lgp171188** [comment] 2015-10-27 18:22
@jdehaan This has been fixed and merged into the ``develop`` branch. Please see the commit 6b431ddd3835b832a5bd3da3b90f17b3d727f8b4

**Comment by areski** [comment] 2015-10-27 22:34
Great fix, I'm closing the ticket. Please reopen @jdehaan f the issue is still present.

**Closed by areski** 2015-10-27 22:34 UTC

**Comment by jdehaan** [comment] 2015-11-11 22:08
Sorry for the poor response time. Thanks for the fix, works great.
